[debug] [2024-06-18T12:41:28.220Z] : 
[debug] [2024-06-18T12:41:28.221Z] : ----------------------------------------------------------------------
[debug] [2024-06-18T12:41:28.221Z] : Command:      C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\bin\catalyst.js serve
[debug] [2024-06-18T12:41:28.222Z] : CLI Version:  1.17.5
[debug] [2024-06-18T12:41:28.222Z] : Platform:     win32
[debug] [2024-06-18T12:41:28.222Z] : Node Version: v20.11.1
[debug] [2024-06-18T12:41:28.222Z] : Time:         Tue Jun 18 2024 18:11:28 GMT+0530 (India Standard Time)
[debug] [2024-06-18T12:41:28.222Z] : ----------------------------------------------------------------------
[debug] [2024-06-18T12:41:28.222Z] : 
[debug] [2024-06-18T12:41:28.719Z] : > authorizing via signed-in user option
[debug] [2024-06-18T12:41:28.719Z] : > command requires scopes: ["ZohoCatalyst.projects.ALL","ZohoCatalyst.functions.ALL","ZohoCatalyst.functions.EXECUTE","ZohoCatalyst.webapp.ALL","ZohoCatalyst.pdfshot.execute"]
[debug] [2024-06-18T12:41:28.728Z] : > refreshing access token <
[debug] [2024-06-18T12:41:28.728Z] : >>>> HTTP REQUEST : POST https://accounts.zoho.com/oauth/v2/token 
<request body omitted>

[warn] [2024-06-18T12:41:29.034Z] : ‼ ETIMEDOUT has occured while communicating remote server. Kindly be patient while the cli retries this request.
[debug] [2024-06-18T12:41:29.034Z] : API Error while firing request : 

[debug] [2024-06-18T12:41:29.034Z] : >>>> RETRYING

[warn] [2024-06-18T12:41:29.296Z] : ‼ ETIMEDOUT has occured while communicating remote server. Kindly be patient while the cli retries this request.
[debug] [2024-06-18T12:41:29.297Z] : API Error while firing request : 

[debug] [2024-06-18T12:41:29.297Z] : >>>> RETRYING

[warn] [2024-06-18T12:41:29.559Z] : ‼ ETIMEDOUT has occured while communicating remote server. Kindly be patient while the cli retries this request.
[debug] [2024-06-18T12:41:29.559Z] : API Error while firing request : 

[debug] [2024-06-18T12:41:29.559Z] : >>>> RETRYING

[warn] [2024-06-18T12:41:29.816Z] : ‼ ETIMEDOUT has occured while communicating remote server. Kindly be patient while the cli retries this request.
[error] [2024-06-18T12:41:29.827Z] : × API Error after retrying : 
[debug] [2024-06-18T12:41:29.828Z] : Error Stack: CatalystError: API Error after retrying : 
    at API.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:162:23)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:27:12)
    at API._retry (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:160:16)
    at API.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:205:56)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
[debug] [2024-06-18T12:41:29.828Z] : Original Error: AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
[debug] [2024-06-18T12:41:29.828Z] : Error Status: 500
[info] [2024-06-18T12:41:29.829Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[error] [2024-06-18T12:41:29.830Z] : × API Error: 
[debug] [2024-06-18T12:41:29.830Z] : Error Stack: CatalystError: API Error: 
    at API.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:214:32)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-06-18T12:41:29.830Z] : Original Error: AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
[debug] [2024-06-18T12:41:29.830Z] : Error Status: 500
[info] [2024-06-18T12:41:29.830Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[error] [2024-06-18T12:41:29.831Z] : × API Error: 
[debug] [2024-06-18T12:41:29.832Z] : Error Stack: CatalystError: API Error: 
    at API.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:214:32)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-06-18T12:41:29.832Z] : Original Error: AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
[debug] [2024-06-18T12:41:29.832Z] : Error Status: 500
[info] [2024-06-18T12:41:29.833Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[error] [2024-06-18T12:41:29.839Z] : × Error when refreshing the access token
[debug] [2024-06-18T12:41:29.840Z] : Error Stack: CatalystError: Error when refreshing the access token
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\credential.js:139:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-06-18T12:41:29.840Z] : Original Error: CatalystError: API Error after retrying : 
    at API.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:162:23)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:27:12)
    at API._retry (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:160:16)
    at API.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:205:56)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
[debug] [2024-06-18T12:41:29.840Z] : Error Status: 500
[info] [2024-06-18T12:41:29.840Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[debug] [2024-06-18T12:41:29.840Z] : EXEC ENDED with event: Error (Unexpected), message: Error when refreshing the access token
[debug] [2024-06-18T12:41:29.840Z] : TOTAL DURATION OF COMMAND EXEC : 1117
[debug] [2024-06-18T12:41:29.841Z] : Unable to initialise the log API
